#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
# Custom Menu Entry for Windows 11, it is vital, that the Windows EFI Partition is mounted under /boot/efi/
# Replace the "Enter your UUID here" with your UUID, prbably looks something like this >> 5EBF-13CA 
if [ "${grub_platform}" == "efi" ]; then
	menuentry "Windows 11" {
		insmod part_gpt
		insmod fat
		insmod search_fs_uuid
		insmod chain
		search --fs-uuid --set=root Enter your UUID here
		chainloader /EFI/Microsoft/Boot/bootmgfw.efi
	}
fi
